name: "property_etl"
version: "1.0.0"

profile: "default"

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

#on-run-end:
#  - "{{ grant_select_on_schemas(['core' 'property_data'], 'reporter_ro') }}"

models:
