version: "3.7"

services:
  proxy:
    env_file: .env
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"

  dynamodb:
    env_file: .env
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]

networks:
  default:
    external:
      name: property-app-net
