default:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 8432
      user: "{{ env_var('LOCAL_DBT_USER') }}"
      pass: "password"
      dbname: amcclosky
      schema: public
    ci:
      type: postgres
      threads: 1
      host: localhost
      port: 6432
      user: "{{ env_var('DBT_USER') }}"
      pass: "{{ env_var('DBT_PASSWORD') }}"
      dbname: property_app
      schema: core
  target: dev
