version: 2

sources:
  - name: tcad
    schema: tcad
    tables:
      - name: parcel

models:
  - name: property
    description: "Property Records"
  - name: property_geometry
    description: "Property Parcel Geometries"
