version: 2

sources:
  - name: permits_austin
    schema: public
    tables:
      - name: permits_austin_20200514

models:
  - name: permit_raw
    description: "Historical and Current Building Permits"
  - name: permit
    description: "Historical and Current Building Permits"
